### ISSUE TITLE
Wrong version format of python3 package fails 4.4 ubuntu/deb tests

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla-python3#12]
All Debian/Ubuntu artifact tests such as https://jenkins.scylladb.com/view/nexts/job/scylla-4.4/job/artifacts/job/artifacts-debian10-test/5/console Fail to install:

23:17:44  The following packages have unmet dependencies:
23:17:44  scylla : Depends: scylla-server (= 4.4~rc0-0.20210119.46e627382-1) but it is not going to be installed
23:17:44  Depends: scylla-jmx (= 4.4~rc0-0.20210119.46e627382-1) but it is not going to be installed
23:17:44  Stderr:
23:17:44  W: --force-yes is deprecated, use one of the options starting with --allow instead.
23:17:44  E: Unable to correct problems, you have held broken packages.
13:22
But I can find the pacakge in http://downloads.scylladb.com/unstable/scylla/branch-4.4/deb/unified/2021-01-19T11:49:20Z/scylladb-4.4/pool/main/s/scylla-server

Looking on the packages on https://jenkins.scylladb.com/job/scylla-4.4/job/unified-deb/3/artifact/scylladb-4.4/pool/main/s/ I see that they include a "~", except for the Python 3 package.
The tilde ("~") is _correct_ on Ubuntu and Debian. It's needed for sorting the version numbers so that "rc" becomes *before* they final "N.M.0" release for "apt".

Takuya, looks like Python build has an issue and forgets to do the conversion. 
cc @penberg

**Comment by syuu1228** [comment]
The fix on scylla-python3 should fix this https://github.com/scylladb/scylla-python3/commit/c579207d6b00b72c58e40156b58822797f6d6c56

**Comment by avikivity** [comment]
It's not enough. Need another patch.
